/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;
import java.awt.Toolkit;
import java.awt.event.KeyListener;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
/**
 *
 * @author MAFOWS21
 */
public class VentanaInicial extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInicial
     */
    private String user1;
    private String user2;
    private int i=0;
   
    
    private int j=0;
    
    
    
    public VentanaInicial() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/ICONOS.png")));
        
        Guardar1.setOpaque(false);
        Guardar1.setContentAreaFilled(false);
        Guardar1.setBorderPainted(false);
        cajaN1.requestFocusInWindow();
        
        acciones();
        acciones2();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        eTitulo = new javax.swing.JLabel();
        eNombre1 = new javax.swing.JLabel();
        Guardar1 = new javax.swing.JButton();
        eNombre2 = new javax.swing.JLabel();
        cajaN1 = new javax.swing.JTextField();
        cajaN2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MICHI PERUANO (BIENVENIDO)");
        setBackground(new java.awt.Color(0, 255, 255));
        setPreferredSize(new java.awt.Dimension(695, 490));
        setResizable(false);

        panel.setBackground(new java.awt.Color(0, 204, 204));
        panel.setFont(new java.awt.Font("Tw Cen MT", 3, 10)); // NOI18N
        panel.setMaximumSize(new java.awt.Dimension(1366, 768));
        panel.setMinimumSize(new java.awt.Dimension(695, 490));
        panel.setPreferredSize(new java.awt.Dimension(0, 0));
        panel.setLayout(null);

        eTitulo.setFont(new java.awt.Font("Elephant", 0, 36)); // NOI18N
        eTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eTitulo.setText("MICHIGLOGLOGLO");
        panel.add(eTitulo);
        eTitulo.setBounds(0, 40, 580, 45);

        eNombre1.setFont(new java.awt.Font("Jokerman", 0, 24)); // NOI18N
        eNombre1.setForeground(new java.awt.Color(255, 0, 0));
        eNombre1.setText("JUGADOR 1:");
        panel.add(eNombre1);
        eNombre1.setBounds(40, 160, 145, 37);

        Guardar1.setFont(new java.awt.Font("Jokerman", 0, 24)); // NOI18N
        Guardar1.setForeground(new java.awt.Color(102, 0, 102));
        Guardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardar1ActionPerformed(evt);
            }
        });
        Guardar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Guardar1KeyReleased(evt);
            }
        });
        panel.add(Guardar1);
        Guardar1.setBounds(130, 100, 480, 7);

        eNombre2.setFont(new java.awt.Font("Jokerman", 0, 24)); // NOI18N
        eNombre2.setForeground(new java.awt.Color(0, 0, 153));
        eNombre2.setText("JUGADOR 2:");
        panel.add(eNombre2);
        eNombre2.setBounds(40, 280, 148, 37);

        cajaN1.setBackground(new java.awt.Color(153, 153, 153));
        cajaN1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        panel.add(cajaN1);
        cajaN1.setBounds(212, 155, 140, 40);

        cajaN2.setBackground(new java.awt.Color(153, 153, 153));
        cajaN2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        panel.add(cajaN2);
        cajaN2.setBounds(212, 275, 140, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/GIF.gif"))); // NOI18N
        panel.add(jLabel1);
        jLabel1.setBounds(420, 170, 250, 141);

        Guardar.setFont(new java.awt.Font("Jokerman", 0, 24)); // NOI18N
        Guardar.setForeground(new java.awt.Color(102, 0, 102));
        Guardar.setText("COMENZAR!!");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        Guardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                GuardarKeyReleased(evt);
            }
        });
        panel.add(Guardar);
        Guardar.setBounds(270, 350, 205, 72);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/GLOGLOSOR.png"))); // NOI18N
        jLabel3.setText(" ");
        panel.add(jLabel3);
        jLabel3.setBounds(540, 20, 79, 73);

        getContentPane().add(panel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        
        //TODO LO DE ABAJO LO COPIAMOS EN EL CODIGO
        user1 = cajaN1.getText();
        user2 = cajaN2.getText();
        ventanaPrincipal ventanaP = new ventanaPrincipal(user1,user2);
        ventanaP.setVisible(true);
        dispose();
        
        
    }//GEN-LAST:event_GuardarActionPerformed

    private void GuardarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_GuardarKeyReleased
        // TODO add your handling code here:
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_GuardarKeyReleased

    private void Guardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Guardar1ActionPerformed

    private void Guardar1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Guardar1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_Guardar1KeyReleased

    
    
    
    private void acciones(){
        
        KeyListener accion1 = new KeyListener(){
            @Override
            public void keyTyped(KeyEvent e) {
                
            }

            @Override
            public void keyPressed(KeyEvent e) {
                
            }

            @Override
            public void keyReleased(KeyEvent e) {
                
                
                
                
                //aca ya presiono enter
                if(e.getKeyChar()=='\n'){
                    
                    
                    
                    if(i==1){
                        
                        if(cajaN1.getText().isEmpty()){
                            //llamamos al boton
                            user1 = cajaN1.getText();
                            user2 = cajaN2.getText();
                            ventanaPrincipal ventanaP = new ventanaPrincipal(user1, user2);
                            ventanaP.setVisible(true);
                            dispose();
                        }
                        else{
                            user1 = cajaN1.getText();
                            user2 = cajaN2.getText();
                            ventanaPrincipal ventanaP = new ventanaPrincipal(user1, user2);
                            ventanaP.setVisible(true);
                            dispose();
                            
                        }
                        
                        
                    }
                    
                    cajaN2.requestFocusInWindow();
                }
                
            }
            
        };
        cajaN1.addKeyListener(accion1);
        
        
        
    }
    private void acciones2(){
        KeyListener accion2 = new KeyListener(){
            @Override
            public void keyTyped(KeyEvent e) {
                
            }

            @Override
            public void keyPressed(KeyEvent e) {
                
            }

            @Override
            public void keyReleased(KeyEvent e) {
                //al momento de presionar enter
                
                /*
                if(j==0 && cajaN2.getText().isEmpty()){
                        cajaN2.requestFocusInWindow();
                        j++;
                    }
                */
                
                while(j<3){
                    j++;
                    if(cajaN2.getText().isEmpty() && j<2){
                        if(e.getKeyChar()=='\n' ){
                            
                            
                            cajaN2.requestFocusInWindow();
                            
                        }
                    }
                    
                    
                }
                
                if(j==3){
                    if(e.getKeyChar()=='\n'){
                    //retornamos el foco de atencion si la caja
                    //N2 esta vacia

                    //si la caja esta vacia
                    
                    
                    
                    
                        
                    
                    if(cajaN1.getText().isEmpty()){
                        
                        //en contandor seria 1
                        i++;
                        cajaN1.requestFocusInWindow();
                    }
                    //si la caja no esta vacia
                    
                    // da igual si la caja 2 esta vacia o no
                    else{
                        //esto es lo mismo que presionar el boton
                        user1 = cajaN1.getText();
                        user2 = cajaN2.getText();
                        ventanaPrincipal ventanaP = new ventanaPrincipal(user1, user2);
                        ventanaP.setVisible(true);
                        dispose();
                        
                    }
                    

                }
                    
                }
                
                
                
            }
            
            
        };
        cajaN2.addKeyListener(accion2);
        
        
    }
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicial().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Guardar1;
    private javax.swing.JTextField cajaN1;
    private javax.swing.JTextField cajaN2;
    private javax.swing.JLabel eNombre1;
    private javax.swing.JLabel eNombre2;
    private javax.swing.JLabel eTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}






